In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Rectangle
import warnings
warnings.filterwarnings('ignore')

In [12]:
import matplotlib.font_manager as font_manager
import matplotlib as mpl
from matplotlib import rcParams

# Definimos path
path = '/home/daniufundar/Documents/Fundar/graficos-indice-desigualdad-genero/'
path = '/Users/danielarisaro/Documents/Fundar/graficos-indice-desigualdad-genero/'

# Definimos fuente para los graficos
font_dir = [path + 'basemaps/Archivo/']
for font in font_manager.findSystemFonts(font_dir):
    font_manager.fontManager.addfont(font)

rcParams['font.family'] = 'Archivo'

# Definimos colores fundar
fundar_colores_primarios = ['#7BB5C4', '#9FC1AD', '#D3D3E0',  '#8d9bff', '#FF9750', '#FFD900',]
fundar_colores_secundarios = ['#B5E0EA', '#B3B3B3', '#848279', '#AFA36E', '#5D896F', '#9C9CBC', '#E27124']
fundar_white = '#F5F5F5'
fundar_black = '#151515'

In [13]:
# Read data

pathdata = '/home/daniu/Documentos/fundar/indice-mercado-trabajo-ingresos/'
pathdata = '/Users/danielarisaro/Documents/fundar/indice-mercado-trabajo-ingresos/'
pathdata = '/home/daniufundar/Documents/Fundar/indice-mercado-trabajo-ingresos/'

df_people_2021 = pd.read_csv(pathdata + 'data_input/personas_tot_urb_3T_21.txt', delimiter=';', low_memory=False)
df_people_2022 = pd.read_csv(pathdata + 'data_input/personas_tot_urb_3T_22.txt', delimiter=';', low_memory=False)

df_houses_2021 = pd.read_csv(pathdata + 'data_input/hogar_tot_urb_3T_2021.txt', delimiter=';', low_memory=False)
df_houses_2022 = pd.read_csv(pathdata + 'data_input/hogar_tot_urb_3T_2022.txt', delimiter=';', low_memory=False)

df_CBT = pd.read_csv(pathdata + 'data_output/Canasta_Basica_Total_Regiones_2016-2022-promedios-moviles.csv', delimiter=',', header=0, index_col=[0])
df_adultos_equiv = pd.read_csv(pathdata + 'data_input/canastas_basicas/adultos_equivalente.csv')

In [14]:
# cod_provincia
dict_cod_provincia = {2: "Ciudad Autónoma de Buenos Aires",
 6: "Buenos Aires",
 10: "Catamarca",
 14: "Córdoba",
 18: "Corrientes",
 22: "Chaco",
 26: "Chubut",
 30: "Entre Ríos",
 34: "Formosa",
 38: "Jujuy",
 42: "La Pampa",
 46: "La Rioja",
 50: "Mendoza",
 54: "Misiones",
 58: "Neuquén",
 62: "Río Negro",
 66: "Salta",
 70: "San Juan",
 74: "San Luis",
 78: "Santa Cruz",
 82: "Santa Fe",
 86: "Santiago del Estero",
 90: "Tucumán",
 94: "Tierra del Fuego, Antártida e Islas del Atlántico Sur"}
#cod_aglomerado

dict_cod_aglomerado = {2: "Gran La Plata",
3: "Bahía Blanca - Cerri",
4: "Gran Rosario",
5: "Gran Santa Fé",
6: "Gran Paraná",
7: "Posadas",
8: "Gran Resistencia",
9: "Comodoro Rivadavia - Rada Tilly",
10:" Gran Mendoza",
12: "Corrientes",
13: "Gran Córdoba",
14: "Concordia",
15: "Formosa",
17: "Neuquén – Plottier",
18: "Santiago del Estero - La Banda",
19: "Jujuy-Palpalá",
20: "Río Gallegos",
22: "Gran Catamarca",
23: "Gran Salta",
25: "La Rioja",
26: "Gran San Luis",
27: "Gran San Juan",
29: "Gran Tucumán - Tafí Viejo",
30: "Santa Rosa – Toay",
31: "Ushuaia - Río Grande",
32: "Ciudad Autónoma de Buenos Aires",
33: "Partidos del GBA",
34: "Mar del Plata",
36: "Río Cuarto",
38: "San Nicolás – Villa Constitución",
91: "Rawson – Trelew",
93: "Viedma – Carmen de Patagones",
40: 'Resto Buenos Aires',
41: 'Resto Catamarca',
42: 'Resto Córdoba',
43: 'Resto Corrientes',
44: 'Resto Chaco',
45: 'Resto Chubut',
46: 'Resto Entre Ríos',
47: 'Resto Formosa',
48: 'Resto Jujuy',
49: 'Resto La Pampa',
50: 'Resto La Rioja',
51: 'Resto Mendoza',
52: 'Resto Misiones',
53: 'Resto Neuquén',
54: 'Resto Río Negro',
55: 'Resto Salta',
56: 'Resto San Juan',
57: 'Resto San Luis',
58: 'Resto Santa Cruz',
60: 'Resto Santa Fe',
61: 'Resto Santiago del Estero',
62: 'Resto Tucumán'}

# Agrego regiones
prov_regiones = pd.DataFrame([
['Ciudad Autónoma de Buenos Aires','CABA', 'Pampeana'],
['Buenos Aires','BA', 'Pampeana'],
['Neuquén', 'NQN', 'Patagonia'],
['Córdoba', 'CBA','Pampeana'],
['San Luis', 'SL', 'Cuyo'],
['Santa Fe', 'SF','Pampeana'],
['Misiones', 'MIS', 'Noreste'],
['La Rioja', 'LR', 'Noroeste'],
['Mendoza', 'MZA', 'Cuyo'],
['Tucumán', 'TUC', 'Noroeste'],
['Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'TDF', 'Patagonia'],
['Entre Ríos', 'ER','Pampeana'],
['La Pampa', 'LP','Pampeana'],
['Chaco', 'CHA', 'Noreste'],
['Río Negro', 'RN', 'Patagonia'],
['San Juan', 'SJ', 'Cuyo'],
['Corrientes', 'COR', 'Noreste'],
['Santiago del Estero', 'SE','Noroeste'],
['Catamarca', 'CAT', 'Noroeste'],
['Salta', 'SAL', 'Noroeste'],
['Formosa', 'FOR', 'Noreste'],
['Chubut', 'CHU', 'Patagonia'],
['Santa Cruz', 'SC', 'Patagonia'],
['Jujuy', 'JU', 'Noroeste']], columns=['Provincia', 'Etiqueta', 'Region'])
prov_regiones = prov_regiones.set_index('Provincia')

map_provincia_region = prov_regiones['Region'].to_dict()

# Agrego regiones
aglom_regiones = pd.DataFrame([
["Gran La Plata", 'Pampeana'],
["Bahía Blanca - Cerri", 'Pampeana'],
["Gran Rosario", 'Pampeana'],
["Gran Santa Fé", 'Pampeana'],
["Gran Paraná", 'Pampeana'],
["Posadas", 'Noreste'],
["Gran Resistencia", 'Noreste'],
["Comodoro Rivadavia - Rada Tilly", 'Patagonia'],
["Gran Mendoza", 'Cuyo'],
["Corrientes", 'Noreste'],
["Gran Córdoba", 'Pampeana'],
["Concordia", 'Pampeana'],
["Formosa", 'Noreste'],
["Neuquén – Plottier", 'Patagonia'],
["Santiago del Estero - La Banda", 'Noroeste'],
["Jujuy-Palpalá", 'Noroeste'],
["Río Gallegos", 'Patagonia'],
["Gran Catamarca", 'Noroeste'],
["Gran Salta", 'Noroeste'],
["La Rioja", 'Noroeste'],
["Gran San Luis", 'Cuyo'],
["Gran San Juan", 'Cuyo'],
["Gran Tucumán - Tafí Viejo", 'Noroeste'],
["Santa Rosa – Toay", 'Pampeana'],
["Ushuaia - Río Grande", 'Patagonia'],
["Ciudad Autónoma de Buenos Aires", 'Gran Buenos Aires'],
["Partidos del GBA", 'Gran Buenos Aires'],
["Mar del Plata", 'Pampeana'],
["Río Cuarto", 'Pampeana'],
["San Nicolás – Villa Constitución", 'Pampeana'],
["Rawson – Trelew", 'Patagonia'],
["Viedma – Carmen de Patagones" 'Patagonia'],
['Resto Buenos Aires', 'Pampeana'],
['Resto Catamarca', 'Noroeste'],
['Resto Córdoba', 'Pampeana'],
['Resto Corrientes', 'Noreste'],
['Resto Chaco', 'Noreste'],
['Resto Chubut', 'Patagonia'],
['Resto Entre Ríos', 'Pampeana'],
['Resto Formosa', 'Noreste'],
['Resto Jujuy', 'Noroeste'],
['Resto La Pampa', 'Pampeana'],
['Resto La Rioja', 'Noroeste'],
['Resto Mendoza', 'Cuyo'],
['Resto Misiones', 'Noreste'],
['Resto Neuquén', 'Patagonia'],
['Resto Río Negro', 'Patagonia'],
['Resto Salta', 'Noroeste'],
['Resto San Juan', 'Cuyo'],
['Resto San Luis', 'Cuyo'],
['Resto Santa Cruz', 'Patagonia'],
['Resto Santa Fe', 'Pampeana'],
['Resto Santiago del Estero', 'Noroeste'],
['Resto Tucumán', 'Noroeste'],],
columns=['Aglomerado', 'Region'])

aglom_regiones = aglom_regiones.set_index('Aglomerado')

map_aglomerado_region = aglom_regiones['Region'].to_dict()

def capitalize_first_letter(s):
    return s.capitalize()

df_CBT = df_CBT.rename(columns=capitalize_first_letter)
df_CBT.rename(columns={'Gran_buenos_aires':'Gran Buenos Aires'}, inplace=True)

In [15]:
# Filter and merge data
df_temp = df_houses_2021.loc[(df_houses_2021['IX_TOT']>1) & (df_houses_2021['REALIZADA']==1) & (~df_houses_2021['NRO_HOGAR'].isin([51, 71]))]
merged_df_2021 = df_people_2021[['CODUSU', 'NRO_HOGAR']].merge(df_houses_2021[['CODUSU', 'NRO_HOGAR']], on=['CODUSU', 'NRO_HOGAR'], how='outer', indicator=True)
duplicated_rows = merged_df_2021['_merge'].value_counts()['both']
rows_people = len(df_people_2021)
hogares_unicos = merged_df_2021[['CODUSU', 'NRO_HOGAR']].value_counts()
count_houses = len(hogares_unicos)
count_viviendas = len(df_temp['CODUSU'].value_counts())

In [16]:
# Create a dictionary with the information
data = {
    'Description': ['Duplicated Rows', 'Total People Rows', 'Total Houses', 'Total Dwellings'],
    'Count': [duplicated_rows, rows_people, count_houses, count_viviendas],
    'Comments': ['Si esta cantidad es la misma a Total People Rows, entonces todos los hogares fueron relevados en la base individual tambien.',
                    'Número de individuos en la encuesta de personas.',
                    'Número de hogares en la encuesta de hogares.',
                    'Número de viviendas únicas']
}

df_counts = pd.DataFrame(data)

In [17]:
def calculate_equivalent_adults(grouped_df, df_adultos_equiv):
    grouped_df['EQUIVALENT_ADULTS'] = 0
    for index, row in grouped_df.iterrows():
        total_equivalent_adults = 0
        for age, gender in zip(row['CH06'], row['CH04']):
            equiv_adults_row = df_adultos_equiv[(df_adultos_equiv['Edad inferior'] <= age) & (df_adultos_equiv['Edad superior'] > age)]
            if not equiv_adults_row.empty:
                equiv_adults = equiv_adults_row.iloc[0]['Mujer'] if gender == 2 else equiv_adults_row.iloc[0]['Varon']
                total_equivalent_adults += equiv_adults
        grouped_df.at[index, 'EQUIVALENT_ADULTS'] = total_equivalent_adults

def merge_and_add_columns(grouped_df, df_houses):
    custom_merged_df = grouped_df.merge(df_houses, on=['CODUSU', 'NRO_HOGAR'], how='left')
    grouped_df['INCOME'] = custom_merged_df['ITF']
    grouped_df['INCOME_PONDERATOR'] = custom_merged_df['PONDIH']
    grouped_df['PROVINCIA'] = custom_merged_df['PROVINCIA']
    grouped_df['AGLOMERADO'] = custom_merged_df['AGLOMERADO']

def reshape_and_filter_data(grouped_df, df_CBT, dict_cod_provincia, dict_cod_aglomerado, map_aglomerado_region):
    melted_df_CBT = df_CBT.melt(id_vars='Trimestre', var_name='Region', value_name='CBT')
    filtered_melted_df_CBT = melted_df_CBT[melted_df_CBT['Trimestre'] == '4T2021']
    grouped_df['Provincia'] = grouped_df['PROVINCIA'].map(dict_cod_provincia)
    grouped_df['Aglomerado'] = grouped_df['AGLOMERADO'].map(dict_cod_aglomerado)
    grouped_df['Region'] = grouped_df['Aglomerado'].map(map_aglomerado_region)
    map_region_CBT = filtered_melted_df_CBT.set_index('Region')['CBT'].to_dict()
    grouped_df['CBT'] = grouped_df['Region'].map(map_region_CBT)
    grouped_df['THRESHOLD'] = grouped_df['CBT'] * grouped_df['EQUIVALENT_ADULTS']

def calculate_poverty_table(df_people, df_houses, df_CBT, df_adultos_equiv, dict_cod_provincia, map_provincia_region):
    grouped_df = df_people.groupby(['CODUSU', 'NRO_HOGAR']).agg({
        'CH03': list,
        'COMPONENTE': list,
        'CH04': list,
        'CH06': list
    })
#    grouped_df = grouped_df[grouped_df['COMPONENTE'].apply(lambda x: 2 not in x)]
    grouped_df['NUM_PEOPLE_IN_HOUSE'] = grouped_df['CH06'].apply(len)
    grouped_df['MEAN_AGE'] = grouped_df['CH06'].apply(lambda ages: sum(ages) / len(ages) if ages else None)
    grouped_df = grouped_df[grouped_df['CH06'].apply(lambda x: any(age < 25 for age in x))]
    grouped_df['GENDER_PERSON_IN_CHARGE'] = grouped_df.apply(lambda row: 'MALE' if 1 in row['CH03'] and row['CH04'][row['CH03'].index(1)] == 1 else 'FEMALE', axis=1)
    grouped_df['PERSON_IN_CHARGE_AGE'] = grouped_df.apply(lambda row: row['CH06'][row['CH03'].index(1)] if 1 in row['CH03'] else None, axis=1)
    grouped_df = grouped_df.reset_index()

    calculate_equivalent_adults(grouped_df, df_adultos_equiv)
    merge_and_add_columns(grouped_df, df_houses)
    reshape_and_filter_data(grouped_df, df_CBT, dict_cod_provincia, dict_cod_aglomerado, map_aglomerado_region)

    return grouped_df

In [18]:
# Calculate poverty table
grouped_df = calculate_poverty_table(df_people_2021, df_houses_2021, df_CBT, df_adultos_equiv, dict_cod_provincia, map_provincia_region)

# Ratios
gender_counts = grouped_df.groupby(['Provincia', 'GENDER_PERSON_IN_CHARGE'])['INCOME_PONDERATOR'].sum().unstack()

# Count rows per province and per gender
row_counts = grouped_df.groupby(['Provincia', 'GENDER_PERSON_IN_CHARGE']).size().unstack()

# Add row counts to gender_counts table
gender_counts['ROW_COUNTS_FEMALE'] = row_counts['FEMALE']
gender_counts['ROW_COUNTS_MALE'] = row_counts['MALE']

# Calculate gender ratios
gender_ratios_2021 = gender_counts['FEMALE'] / gender_counts['MALE']

# Display the gender ratios
gender_counts

GENDER_PERSON_IN_CHARGE,FEMALE,MALE,ROW_COUNTS_FEMALE,ROW_COUNTS_MALE
Provincia,,,,
Buenos Aires,1294488,1925040,730,946
Catamarca,29195,33670,253,286
Chaco,74489,125264,178,237
Chubut,48937,65933,286,359
Ciudad Autónoma de Buenos Aires,264203,326224,81,104
Corrientes,80842,99542,205,249
Córdoba,410307,246740,557,390
Entre Ríos,119202,132587,341,404
Formosa,59362,35418,279,183
Jujuy,64022,60516,329,302
La Pampa,24869,32354,120,114
La Rioja,34512,34545,283,269
Mendoza,112061,179925,227,359
Misiones,63599,143088,170,354
Neuquén,58435,59549,235,218
Río Negro,69144,70946,277,262
Salta,109552,125707,406,407
San Juan,44143,77536,195,355
San Luis,35159,48060,212,296
Santa Cruz,28812,46579,156,179
Santa Fe,244761,364662,381,500
Santiago del Estero,55917,77332,268,332
"Tierra del Fuego, Antártida e Islas del Atlántico Sur",14573,19985,84,115
Tucumán,86158,162416,257,462

In [19]:
# Calculate poverty table
grouped_df = calculate_poverty_table(df_people_2022, df_houses_2022, df_CBT, df_adultos_equiv, dict_cod_provincia, map_provincia_region)

# Ratios
gender_counts = grouped_df.groupby(['Provincia', 'GENDER_PERSON_IN_CHARGE'])['INCOME_PONDERATOR'].sum().unstack()

# Count rows per province and per gender
row_counts = grouped_df.groupby(['Provincia', 'GENDER_PERSON_IN_CHARGE']).size().unstack()

# Add row counts to gender_counts table
gender_counts['ROW_COUNTS_FEMALE'] = row_counts['FEMALE']
gender_counts['ROW_COUNTS_MALE'] = row_counts['MALE']

# Calculate gender ratios
gender_ratios_2022 = gender_counts['FEMALE'] / gender_counts['MALE']

# Display the gender ratios
gender_counts

GENDER_PERSON_IN_CHARGE,FEMALE,MALE,ROW_COUNTS_FEMALE,ROW_COUNTS_MALE
Provincia,,,,
Buenos Aires,1359321,2067668,920,1151
Catamarca,34928,28880,263,253
Chaco,84422,110357,216,222
Chubut,51757,64931,260,306
Ciudad Autónoma de Buenos Aires,291704,303509,120,164
Corrientes,76190,108623,175,232
Córdoba,352540,300719,506,405
Entre Ríos,109835,134873,290,381
Formosa,54821,38055,240,155
Jujuy,68741,60980,344,280
La Pampa,29579,27867,195,171
La Rioja,30574,36617,255,274
Mendoza,117025,169739,232,323
Misiones,74292,137195,178,328
Neuquén,63299,57533,207,200
Río Negro,60629,75975,245,293
Salta,120305,119292,368,348
San Juan,46596,75986,195,316
San Luis,32359,51320,190,278
Santa Cruz,41131,36052,158,142
Santa Fe,266828,343671,392,453
Santiago del Estero,63316,66555,282,275
"Tierra del Fuego, Antártida e Islas del Atlántico Sur",15844,18709,91,100
Tucumán,97459,162907,279,463

In [21]:
df_ratio = (gender_ratios_2021 + gender_ratios_2022)/2

In [22]:
df_ratio

Provincia
Buenos Aires                                             0.664932
Catamarca                                                1.038255
Chaco                                                    0.679823
Chubut                                                   0.769665
Ciudad Autónoma de Buenos Aires                          0.885494
Corrientes                                               0.756778
Córdoba                                                  1.417618
Entre Ríos                                               0.856703
Formosa                                                  1.558307
Jujuy                                                    1.092603
La Pampa                                                 0.915044
La Rioja                                                 0.917006
Mendoza                                                  0.656131
Misiones                                                 0.492991
Neuquén                                                  1.040757
Río Negro                                                0.886306
Salta                                                    0.939989
San Juan                                                 0.591270
San Luis                                                 0.681049
Santa Cruz                                               0.879721
Santa Fe                                                 0.723802
Santiago del Estero                                      0.837205
Tierra del Fuego, Antártida e Islas del Atlántico Sur    0.788031
Tucumán                                                  0.564363
dtype: float64